### ISSUE TITLE
Fatal error when analysing t3jquery.txt in extensions - also current git version

### ISSUE THREAD

**Issue by web2date** [typo3-themes/t3jquery#3]
Fatal error: Class 'analyzeJqJS' not found in /home/www/pxxxxxx/html/typo3conf/ext/t3jquery/Classes/Module/index.php on line 505

**Comment by kaystrobach** [comment]
typo3 cache cleared? - how have you generated that error?

**Comment by web2date** [comment]
Hi, I tried to analyse "Find the jQuery Components you need" in the t3jquery Backend module...choose bootstrap theme and themes and say CHECK....

**Comment by web2date** [comment]
typo3 cache cleared also in Installtool before...no change...same error
