### ISSUE TITLE
module t3jquery > process and analyte t3jquery.txt in extensions does not work on 7.6.2

### ISSUE THREAD

**Issue by erredeco** [typo3-themes/t3jquery#5]
I use TYPO3 7.6.2 and the latest t3jquery from TER

when I access the module " t3jquery > process and analyte t3jquery.txt in extensions" I see the error:

```
ERROR: Extensions path: "/Sites/typo3.7.development.it/typo3/ext/" not found!
```

that should be `typo3conf/ext` I guess..

**Comment by martinwb** [comment]
Same problem here ...

**Comment by kaystrobach** [comment]
are you able to find the place where the error occurs, i assume, that an deprected constant is used there

**Comment by FR-95** [comment]
Is there a solution for this still existing problem? 
![bildschirmfoto 2016-08-09 um 13 35 13](https://cloud.githubusercontent.com/assets/13747539/17515024/453f79e4-5e36-11e6-93d6-0e79c9437e60.png)

**Comment by kaystrobach** [comment]
- is that problem still existing with current master?
- which php and TYPO3 version are you using exactly?

**Comment by kaystrobach** [comment]
to get it fixed fast, there are 2 options:
1. sponsor 1h of my time (you will get an proper invoice)
2. send a pull request

If you do the first, I'm pretty sure i can find the problem within this week and fix it.

Otherwise i will fix it, once I find the time to work on it ... 😢

**Comment by FR-95** [comment]
- t3jquery 3.0.3 
- Typo3 7.6.10 
- PHP 5.6.24

i PM you 
thx

**Comment by kaystrobach** [comment]
@DonChef660 got no PM 😢

**Comment by DonChef660** [comment]
Sorry didnt work on that project since then. i checked this case with my superior he said that its in no rush that means we propably cant pay for it :/
But im gonna ask a another customer if he needs it and wants to pay. How much would it cost though?


Best regards
